### ISSUE TITLE
LLVM fails to build again

### ISSUE THREAD

**Issue by jbigot** [pdidev/test_env#5]
See https://github.com/pdidev/test_env/runs/5808863050

This time, this is likely due to https://github.com/spack/spack/issues/29751

**Comment by bernhardkaindl** [comment]
Yes, it's an issue in upstream LLVM version 14 which they didn't notice.

A workaround was to select an older LLVM by adding ^llvm@13 to the build.

The fix by https://s-sajid-ali.github.io is merged in spack now to fix it for users of spack.

You can update to current spack for this build fix for llvm-14.0.0 now.

**Comment by jbigot** [comment]
Thank you very much for the update, will do!

**Comment by jbigot** [comment]
Fixed, thanks @bernhardkaindl
